### ISSUE TITLE
ExternalAsciiStringResource is gone in upstream V8

### ISSUE THREAD

**Issue by bnoordhuis** [rvagg/nan#222]
Replaced in v8/v8-git-mirror@299ed09 with 'ExternalOneByteStringResource`.  Not sure about the exact version because the V8 people don't tag properly but it was probably a 3.28 release.

This affects iojs because it ships V8 3.30.  I'll try to come up with a patch.

**Comment by rlidwka** [comment]
Any progress on resolving this?

I'm trying to port my binary packages to work under io.js when it's released, and this issue is a blocker. :(

**Comment by bnoordhuis** [comment]
@rlidwka I updated #223, PTAL.
