### ISSUE TITLE
Changes in v8 between joyent/0.11.14 and io.js/1.0

### ISSUE THREAD

**Issue by kkoopa** [rvagg/nan#225]
The following utility functions have moved from `v8::V8` to `v8::Isolate`

V8 -> Isolate
-----------------------------------------------------
*** moved, but deprecated remains
%%% deprecated and moved before v8 @ 0.11.14, ignore
### removed
-----------------------------------------------------
AddMessageListener ***
RemoveMessageListeners ***
SetCaptureStackTraceForUncaughtExceptions ***

SetCounterFunction
SetCreateHistogramFunction
SetAddHistogramSampleFunction

SetFailedAccessCheckCallbackFunction ***

AddGCPrologueCallback ***
RemoveGCPrologueCallback ***
AddGCEpilogueCallback ***
RemoveGCEpilogueCallback ***

AddMemoryAllocationCallback ***
RemoveMemoryAllocationCallback ***

RunMicrotasks %%%
EnqueueMicrotask %%%
SetAutorunMicrotasks %%%

SetFunctionEntryHook ###
SetJitCodeEventHandler

TerminateExecution ***
IsExecutionTerminating ***
CancelTerminateExecution ***

VisitExternalResources ***
VisitHandlesWithClassIds ***
VisitHandlesForPartialDependence ***

IdleNotification
LowMemoryNotification
ContextDisposedNotification

**Comment by rvagg** [comment]
this looks like work for 1.6

**Comment by kkoopa** [comment]
Only those without special markings are strictly necessary. They are quite easy to address. I'll see what can be done. Those that have deprecated holdouts lying around can still be used for the time being.

**Comment by ReklatsMasters** [comment]
`String::New` was removed. Empty constructor `Object::New()` was removed.
We need compability layer.

**Comment by kkoopa** [comment]
`String::New` was removed a long time ago already, maybe in the version v8 that was in 0.11.13, or even before that. The Object constructor has definitely not been removed.
