### ISSUE TITLE
Add @agnat as collaborator

### ISSUE THREAD

**Issue by rvagg** [rvagg/nan#230]
I'd like to add @agnat as a collaborator now that his changes have landed and are released, if there are objections from existing collaborators please speak up (or email me directly).

**Comment by kkoopa** [comment]
I guess there were no objections. Will you make it so?

**Comment by rvagg** [comment]
oh, derp, indeed! adding you now @agnat, welcome on board and thanks for your contributions so far! Please follow along with the pattern here or having every change made via PR with enough time to get reviews by others across the timezones.

**Comment by rvagg** [comment]
@agnat would you also mind adding yourself to nan.h, package.json and README.md please? via PR of course!
