### ISSUE TITLE
nan/nan_new.h:184:10: error: call to 'New' is ambiguous

### ISSUE THREAD

**Issue by KenanSulayman** [rvagg/nan#233]
Hey,

trying to migrate my modules to io.js (1.0.1) and upgraded nan to 1.5.1; however, the following now appears when compiling the module:

	In file included from ../src/couchbase_impl.cc:21:
	In file included from ../src/couchbase_impl.h:40:
	In file included from ../node_modules/nan/nan.h:63:
	../node_modules/nan/nan_new.h:184:10: error: call to 'New' is ambiguous
	  return NanIntern::Factory<T>::New(arg0);
	         ^~~~~~~~~~~~~~~~~~~~~~~~~~
	../src/module_impl.cc:171:43: note: in instantiation of function template specialization 'NanNew<v8::Integer, unsigned long long>' requested here
	        resObj->Set(NanNew(me->valueKey), NanNew<Integer>(resp->v.v0.value));
	                                          ^
	../node_modules/nan/nan_new.h:86:26: note: candidate function
	  static inline return_t New(int32_t value);
	                         ^
	../node_modules/nan/nan_new.h:87:26: note: candidate function
	  static inline return_t New(uint32_t value);

Looks like an Apple-gcc/llvm 4.2.1 specific issue, though.

Env:

	Gcc:
		Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
		Target: x86_64-apple-darwin14.1.0

	Release:
		Darwin 14.1.0; root:xnu-2782.10.72~4/RELEASE_X86_64

	nan ~1.5.1

Thanks

**Comment by rvagg** [comment]
likely bundled up with the same problem as #227, your options probably look like this:
 - be explicit in which template you're targetting: `NanNew<Something>(args)`
 - roll back to 1.4.3, that supports io.js which I believe you're after
 - wait for a patch release to fix this, I'm sure @kkoopa and @agnat will be on to it shortly

**Comment by kkoopa** [comment]
Here it is definitely a case of a 64-bit variable, it clearly says unsigned 
long long. V8 has never supported 64-bit integers, you need to downcast it to 
a 32-bit value.

We won't be doing any silent downcasting, as that would be very dangerous and 
wrong. It's a feature, not a bug.

**Comment by rvagg** [comment]
well then, that's that!

**Comment by agnat** [comment]
I agree with @kkoopa. This is _exactly_ the kind of issue the `NanNew(...)` rewrite targets. The old code came up with some crazy silent truncating and potentially dangerous conversion.

The right thing to do is:

1. check that `resp->v.v0.value` is a valid JS integer (<1e53 - 1 IIRC)
2. truncate manually to `uint_32`

**Comment by agnat** [comment]
Uh... forget number 2.

The right thing to do is to use `NanNew<Number>(...)` if the number can ever be larger than `uint_32`....

**Comment by kkoopa** [comment]
But note that it only takes a double, and a double can't represent integers 
larger than 2^53.

**Comment by agnat** [comment]
> [...] (<1e53 - 1 IIRC)

2^53 is correct. I _really_ should get more coffee. :-/

**Comment by Kagami** [comment]
Had the same problem, replaced `NanNew<Number>` with `NanNew<Number>` ant it works. https://github.com/bitchan/bitmessage/commit/ecdcd30a761588b92a04767f93b973b4cd712973#diff-c5e3109b5f05c63b16cfefb07ce3b079L13

>V8 has never supported 64-bit integers, you need to downcast it to a 32-bit value.

Hm, but how it works before with Integer? Was it doing implicit convertion between int64 and int32? Also Integer type supports export to the int64_t: http://izs.me/v8-docs/classv8_1_1Integer.html

**Comment by kkoopa** [comment]
It probably did implicit downcasting. Depends on the compiler if it warned or 
not. Strangely, this is one area where msvc usually was stricter than gcc.

It supports exporting to a 64-bit integer yes, so that you can get your 2^53 
from a double. But not importing a 64-bit integer, for that you need to cast 
to a double, which, as previously noted, only holds up to 2^53.

**Comment by bnoordhuis** [comment]
> Was it doing implicit convertion between int64 and int32?

Yes.

> Also Integer type supports export to the int64_t

That's because a v8::Integer sometimes really is a v8::Number.

**Comment by kkoopa** [comment]
Yes, one of the less sane ideas of JavaScript was to use doubles for 
everything. Now people are trying to [add static types]
(http://www.typescriptlang.org/).
