### ISSUE TITLE
1.5.1 broken with node-webkit's nw-gyp

### ISSUE THREAD

**Issue by aspoon** [rvagg/nan#249]
I have been using `nan` with both node.js and node-webkit (now nwjs.io) on Windows.  node-webkit uses its own fork of `node-gyp` called `nw-gyp` to build modules.

I've just upgraded `nan` from 1.3.x to 1.5.1 (latest), and `nw-gyp` complains: (while `node-gyp` compiles fine)

```
C:\...\>nw-gyp rebuild --target=0.11.5
...
[...]\node_modules\nan\nan.h(1471): error C2664: 'uv_async_init' : cannot convert parameter 3 from 'void (__cdecl *)(uv_async_t *)' to 'uv_async_cb' [....vcxproj]
          None of the functions with this name in scope match the target type
...
```

The `--target=0.11.5` refers to the node-webkit version, and is required due to the inability to detect the actual version in use automatically.  It was compiling just fine with 1.3.x.  And BTW, I don't use async worker in my code.

**Comment by kkoopa** [comment]
Will be fixed in the next patch release. #245
