### ISSUE TITLE
Add support for node::Encode/DecodeBytes/DecodeWrite

### ISSUE THREAD

**Issue by royaltm** [rvagg/nan#250]
Could you add support for those handy utils?

```cpp
#if NODE_VERSION_AT_LEAST(0,11,12)
#define NanEncode(buf, buflen, encoding) \
  node::Encode(v8::Isolate::GetCurrent(), buf, buflen, encoding)
#define NanDecodeBytes(val, encoding) \
  node::DecodeBytes(v8::Isolate::GetCurrent(), val, encoding)
#define NanDecodeWrite(buf, buflen, val, encoding) \
  node::DecodeWrite(v8::Isolate::GetCurrent(), buf, buflen, val, encoding)
#else
#define NanEncode(buf, buflen, encoding) \
  node::Encode(buf, buflen, encoding)
#define NanDecodeBytes(val, encoding) \
  node::DecodeBytes(val, encoding)
#define NanDecodeWrite(buf, buflen, val, encoding) \
  node::DecodeWrite(buf, buflen, val, encoding)
#endif
```

**Comment by kkoopa** [comment]
Probably. Were they around in Node 0.8?

**Comment by bnoordhuis** [comment]
Yes.  All three have been around since the dawn of time (or node v0.3, whatever came first.)

**Comment by kkoopa** [comment]
Only problem seems to be that 0.8 does not support the `BUFFER` encoding. Backporting is feasible.

**Comment by royaltm** [comment]
Is really backporting an issue here? I'm using those to provide compatibility of 
F(string, encoding) -> binary
G(binary, encoding) -> string
as in new Buffer(string, encoding), or buffer.toString(encoding).
So if particular version of node doesn't support some encoding, why otherwise it should? Unless you want to polyfill all native string+encoding functions.

**Comment by kkoopa** [comment]
See #251.

**Comment by royaltm** [comment]
Looks great!
