### ISSUE TITLE
Function.length

### ISSUE THREAD

**Issue by kkoopa** [rvagg/nan#260]
Is it at all possible to backport the length argument for FunctionTemplate?
It is supposed to set the length property of resulting functions to the number of expected arguments.
It was introduced in one of the newer v8 versions, but I think the property is part of the ES5 standard. 

What changed in ES6 seems to be that it is now supposed to be configurable, presumably through Object.setOwnProperty.

In [some v8-dev discussion](https://codereview.chromium.org/116083006/) I saw, they mentioned that this lead to some complications for them, (maybe the term was shadowing). This could be why the property is implemented as an accessor pair.

Would it not then be possible to hack up a solution by creating a FunctionTemplate without specified length and then manipulating its associated ObjectTemplate, adding a function returning the desired length, obtained through a template parameter, as the getter and a no-op function as the setter, before finally returning this Frankenstein's Monster to the user?

pseudocode
```c++
template <int I> NAN_GETTER(NanLengthGetter_) { return v8::Integer::New(I); }
NAN_SETTER(NanLengthSetter_) {}

NanNewFunctiontemplate(InvocationCallback callback=0, Handle< Value > data=Handle< Value >(), Handle< Signature > signature=Handle< Signature >(), int length) {
v8::Local<v8::FunctionTemplate> tpl = v8::FunctionTemplate::New(callback, data, signature);

tpl->InstanceTemplate()->SetAccessor (v8::String::New("length"), NanLengthGetter_<length>, NanLengthSetter_, Handle< Value >(), DEFAULT, static_cast<v8::PropertyAttribute>(v8::ReadOnly | v8::DontEnum));

return tpl;
}
```

Am I missing something important here?
Is it at all feasible?
Is there a simpler way?

@bnoordhuis: Perhaps you can shed some light on this?

**Comment by bnoordhuis** [comment]
> Is it at all feasible?

I don't think so.  The .length property is effectively hard-coded into the function object instance with V8 3.14.

> Is there a simpler way?

Not expose a way to set .length? :-)

**Comment by kkoopa** [comment]
I guess that is it indeed it then. Nothing seems to work for this particular property.
