### ISSUE TITLE
Problem with NPM Publish?

### ISSUE THREAD

**Issue by No9** [rvagg/nan#263]
Hi @rvagg  
So https://github.com/ddopson/node-segfault-handler/issues/20 seem to be caused by a publish issue in npm? 

```
npm install nan@1.5.1 
ls node_modules/nan/*.js
```
Outputs 
`node_modules/nan/include_dirs.js`
As expected 

However
```sh
$ rm node_modules/nan -fr
$ npm install nan@1.5.2
$ ls node_modules/nan/*.js
```
Returns nothing :( 

Can we have a 1.5.3 that is the same as 1.5.2 but with the missing `include_dirs.js`
Or a controversial republish of 1.5.2 if that's possible?

We would just bump to 1.6.1 but that is a breaking change

Thoughts and HALP always appreciated.

**Comment by rvagg** [comment]
yeah, was already done in #262
