### ISSUE TITLE
NanNew<v8::Integer>(size_t) compile problem

### ISSUE THREAD

**Issue by BloodAxe** [rvagg/nan#270]
Hello,

I'm having build issues when trying to return an integer of size_t from NaN (latest version):

    NAN_METHOD(ImageView::Stride)
    {
        SETUP_FUNCTION(ImageView);
        size_t stride = self->mImage.step[0];
        NanReturnValue(NanNew<v8::Integer>(stride));
    }

This leads to compile-time error:

    ../node_modules/nan/nan_new.h:209:10: error: call to 'New' is ambiguous
      return NanIntern::Factory<T>::New(arg0);
             ^~~~~~~~~~~~~~~~~~~~~~~~~~
    ../src/framework/Image.cpp:174:24: note: in instantiation of function template
          specialization 'NanNew<v8::Integer, unsigned long>' requested here
            NanReturnValue(NanNew<v8::Integer>(stride));
                           ^
    ../node_modules/nan/nan.h:835:51: note: expanded from macro 'NanReturnValue'
    # define NanReturnValue(value) return scope.Close(value)
                                                      ^
    ../node_modules/nan/nan_new.h:109:26: note: candidate function
      static inline return_t New(int32_t value);
                             ^
    ../node_modules/nan/nan_new.h:110:26: note: candidate function
      static inline return_t New(uint32_t value);

Can you fix that please? Thanks!

**Comment by kkoopa** [comment]
No, you cannot return a 64-bit unsigned int. It is not supportedby v8.
