### ISSUE TITLE
Emit System Error?

### ISSUE THREAD

**Issue by achingbrain** [rvagg/nan#281]
I was having a go at porting melor/node-posix#30 to run on node 0.12/io.js and it had code like this:

```cc
if(chdir(*dir_path)) {
  return ThrowException(ErrnoException(errno, "chroot: chdir: "));
}
```

When `dir_path` referred to a non-existent directory, this resulted in the thrown JavaScript Error object having a `code` property with the string value `ENOENT` and an `errno` property with the value `2`.  I translated it to:

```cc
if(chdir(*dir_path)) {
  return NanThrowError("chroot: chdir: ", errno);
}
```

`code` then had the value `2` and no `errno` property, which is less useful.

Is there an easy way to get the code translated to a string with nan?  Or does there need to be a new `NanThrowSystemError` macro or similar?

**Comment by kkoopa** [comment]
Currently there is no easy way. The ErrnoException function does many things. 
https://github.com/iojs/io.js/blob/v1.x/src/node.cc#L712-755 There would have 
to be a new NanSomething.

**Comment by bnoordhuis** [comment]
Seeing how you're already using errno, can't you do e.g. `NanThrowError(strerror(errno))`?

**Comment by achingbrain** [comment]
Perhaps.  But if I do that I only get a `message` property on the Error object with the value `No such file or directory` - no `code`, no `errno` and no way of adding any extra contextual information to make it easier to work out what went wrong.

**Comment by kkoopa** [comment]
Just set up something similar to `NanError(const char *msg, const int errorNumber)`. You can quite easily add all sorts of properties to the error object. Finally, throw the error object using `NanThrowError`.

**Comment by achingbrain** [comment]
If I do:

```cc
return NanThrowError(NanError("my message", errno));
```

I get:

```javascript
{
  message: 'my message',
  code: 2,
  stack: '...'
}
```

So, a magic number for `code` and no actual error message other than what I provide.

If I do:

```cc
return ThrowException(ErrnoException(errno, "my message"));
```

I get:

```javascript
{
  message: 'my message',
  code: 'ENOENT',
  errno: 2,
  stack: '...'
}
```

The magic number is in the `errno` property and a friendly(ish) string is in `code`.

I guess what I really want is something a bit like a [System Error](https://iojs.org/api/errors.html#errors_system_errors), so I'd do:

```cc
return NanThrowSystemError("my message", errno);
```

And get get:

```javascript
{
  message: 'my message',
  code: 'ENOENT',
  errno: 2,
  stack: '...'
}
```

I'd rather not have to set up each property of the error object every time because it will become very verbose very quickly.

**Comment by kkoopa** [comment]
This is too POSIX-specific. It is unlikely to happen. Best way is to write your own utility function which does what you want and then use that.
