### ISSUE TITLE
nan.h file

### ISSUE THREAD

**Issue by kurapatijayaram** [rvagg/nan#282]
nan.h files was updated four days ago to support atom shell .... but how to get those changes to my system ? can I copy the file simply? or ?

Thank u :-)

**Comment by mathiask88** [comment]
Just clone from master or wait for the 1.7.0 release in 1-2 weeks

**Comment by kurapatijayaram** [comment]
Ya .... Its a dependency for another module. So I simply added git url instead of version number. Now it is working fine ....

Thank u :-)
