### ISSUE TITLE
Set number of threads processing NanAsyncWorker jobs 

### ISSUE THREAD

**Issue by jjpepper** [rvagg/nan#286]
Hi,
Is it possible to set the number of threads that are executing the tasks queued up using NanAsyncQueueWorker.  I'd like to have one worker thread in the pool at the moment, to work around a multithreading issue with a C library I'm calling into.  Is this easy to do?

Cheers,
Jesse

**Comment by springmeyer** [comment]
This is controlled via `UV_THREADPOOL_SIZE` environment setting, so just set that before you start your node app.

I usually doing something like:

```js
process.env.UV_THREADPOOL_SIZE = Math.ceil(Math.max(4, require('os').cpus().length * 1.5));
```

At the very top of the node script that starts my app.

**Comment by jjpepper** [comment]
Thanks :-)

On Tue, Feb 24, 2015 at 12:02 PM, Dane Springmeyer <notifications@github.com
> wrote:

> This is controlled via UV_THREADPOOL_SIZE environment setting, so just
> set that before you start your node app.
>
> I usually doing something like:
>
> process.env.UV_THREADPOOL_SIZE = Math.ceil(Math.max(4, require('os').cpus().length * 1.5));
>
> At the very top of the node script that starts my app.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rvagg/nan/issues/286#issuecomment-75695986>.
>



-- 
Jesse Pepper

Director

Think Bottom Up Pty Ltd

e: jesse.pepper@thinkbottomup.com.au
m: +61 4 2467 5865
t: +61 8 6460 1643
f: +61 8 6210 1175
16/9 Vale St, Malaga,
Western Australia 6090

**Comment by unbalanced** [comment]
Bumping this thread, 
It seems that setting process.env.UV_THREADPOOL_SIZE does not work in my use case while setting the environment variable from the shell does work.
Any clue what wrong? i really want to set the threadpool from the inside of the app (at the first line)

**Comment by bnoordhuis** [comment]
@unbalanced Write a wrapper script that starts the real script with `child_process.spawn({ env: { UV_THREADPOOL_SIZE: size } });`.  Setting it from the script itself isn't guaranteed to work.

**Comment by springmeyer** [comment]
@unbalanced - that is interesting. What node version and operating system are you seeing this on? Also how are you determining that it is not working?

**Comment by unbalanced** [comment]
I'm using node 6.9.1 (32bit) on windows 10
My app is using a native module that needs an extended threadpool.

When i'm simply running
```
node app.js
```
and using process.env.UV_THREADPOOL_SIZE = 6
i see no change from the default threadpool size...

When running:
```
UV_THREADPOOL_SIZE=6 node app.js
```
The change within the app is noticeable

**Comment by z008hy** [comment]
why my app UV_THREADPOOL_SIZE invalid
`
var fs = require('fs');
var util = require('util');

var start = process.hrtime();

for (var i = 0; i < 1008; ++i) {
    (function (id) {
        fs.readdir('.', function () {
            var end = process.hrtime(start);
            console.log(util.format('readdir %d finished in %ds', id, end[0] + end[1] / 1e9));
        });
    })(i);
}
`
result
![image](https://user-images.githubusercontent.com/20768496/31711505-f8d6fe86-b3bd-11e7-9142-4e68dc5d4cfd.png)
`
process.env.UV_THREADPOOL_SIZE = 32
var fs = require('fs');
var util = require('util');

var start = process.hrtime();

for (var i = 0; i < 100; ++i) {
    (function (id) {
        fs.readdir('.', function () {
            var end = process.hrtime(start);
            console.log(util.format('readdir %d finished in %ds', id, end[0] + end[1] / 1e9));
        });
    })(i);
}
`
result
![image](https://user-images.githubusercontent.com/20768496/31711538-174fcbf4-b3be-11e7-8e6e-ac96bfff208e.png)
node 7.8.0
os macosx
