### ISSUE TITLE
NODE_MODULE where initialization function takes two arguments

### ISSUE THREAD

**Issue by SkyLined** [rvagg/nan#290]
I'm running into errors when attempting to compile my code for Node.js <= v0.9.7. It appears that the initialization function passed to NODE_MODULE cannot have two arguments in earlier versions. I was unable to find anything about solving this in the Nan documentation. Is it possible to do this with Nan? If not, can this be added to Nan?

Relevant part of my code:

```
cWinPerfCounter.cpp:
<snip>
void init(Handle<Object> exports, Handle<Object> module) {
  cWinPerfCounter::fInit(module);
}

NODE_MODULE(cWinPerfCounter, init)
```
Error: 
`..\src\cWinPerfCounter.cpp(102): error C2440: 'initializing' : cannot convert from 'void (__cdecl *)(v8::Handle<v8::Object>,v8::Handle<v8::Object>)' to 'void (__cdecl *)(v8::Handle<v8::Object>)' [H:\dev\node\cWinPerfCounter\build\cWinPerfCounter.vcxproj]`

**Comment by kkoopa** [comment]
I am afraid that is not possible. This was added in joyent/node@15508589a163b0c9f09ac608281f9ebb015d4deb and is a change in runtime behavior.

**Comment by SkyLined** [comment]
That is unfortunate. Luckily, you can easily work around this by:
1. adding a .js that serves as your main script
2. Have this .js load your addon
3. Rewrite your initialization routine to take only the "exports" argument and make changes to it.
4. Have the .js apply whatever changes your addon would like to make to the "module" based on what was changed in the "exports".
e.g. You could add a property "module" to "exports" in your addon and have the .js copy that to the real "module". I've tested this with 0.8.9 and it seems to work just fine.
