### ISSUE TITLE
example of calling method from NanAsyncWorker

### ISSUE THREAD

**Issue by mbroadst** [rvagg/nan#293]
I'm trying to develop an addon that processes a large number of messages infinitely, and emits those messages as they come in. I thought I could achieve this by using a NanAsyncWorker and having the addon inherit EventEmitter, but I just can't seem to get it working. I was wondering if you had any examples of making those types of calls from the async workers? (NanAsyncProgressWorker seems to be along the lines of what I'm looking for, but not quite). So far I've got this code which crashes every time (clearly due to my lack of knowledge of the memory model): 

```c++
#include <nan.h>

#ifndef _WIN32
#include <unistd.h>
#define Sleep(x) usleep((x)*1000)
#endif

using namespace v8;

class AsyncEmitter : public node::ObjectWrap
{
public:
  static void Init(Handle<Object> exports);

private:
  explicit AsyncEmitter();
  virtual ~AsyncEmitter();

  static Persistent<Function> constructor;
  static NAN_METHOD(New);
  static NAN_METHOD(Start);

};

Persistent<Function> AsyncEmitter::constructor;
AsyncEmitter::AsyncEmitter()
{
};

AsyncEmitter::~AsyncEmitter()
{
};

void AsyncEmitter::Init(Handle<Object> exports)
{
  NanScope();

  // constructor
  Local<FunctionTemplate> tpl = NanNew<FunctionTemplate>(AsyncEmitter::New);
  tpl->SetClassName(NanNew("AsyncEmitter"));
  tpl->InstanceTemplate()->SetInternalFieldCount(1);

  // prototype
  NODE_SET_PROTOTYPE_METHOD(tpl, "start", AsyncEmitter::Start);

  NanAssignPersistent(constructor, tpl->GetFunction());
  exports->Set(NanNew("AsyncEmitter"), tpl->GetFunction());
}

// v8 exposed methods
NAN_METHOD(AsyncEmitter::New)
{
  NanScope();
  AsyncEmitter *object = new AsyncEmitter();
  object->Wrap(args.This());
  NanReturnValue(args.This());
}

class Worker : public NanAsyncWorker
{
public:
  Worker(NanCallback *callback, AsyncEmitter *emitter)
    : NanAsyncWorker(callback),
      m_emitter(emitter)
  {}
  ~Worker() {}

  void Execute() {
    Sleep(1000);

    Local<Value> argv[] = {
      NanNew<String>("test message")
    };

    Local<Object> emitter = NanNew<Object>(m_emitter->persistent());
    NanMakeCallback(emitter, "emit", 1, argv);

    Sleep(1000);
  }

private:
  AsyncEmitter *m_emitter;

};

NAN_METHOD(AsyncEmitter::Start)
{
  NanScope();
  AsyncEmitter *asyncEmitter = ObjectWrap::Unwrap<AsyncEmitter>(args.This());
  NanCallback *callback = new NanCallback(args[1].As<v8::Function>());
  NanAsyncQueueWorker(new Worker(callback, asyncEmitter));
  NanReturnUndefined();
}

void InitAll(Handle<Object> exports) {
  AsyncEmitter::Init(exports);
}

NODE_MODULE(addon, InitAll)
```

Any advice would be greatly appreciated, and I'm more than willing to package this up into an example/test case PR.

**Comment by mbroadst** [comment]
I've got a repo up [here](https://github.com/mbroadst/async-emitter) for anyone who wants to play around with the code

**Comment by bnoordhuis** [comment]
The bug in your code is that you call into V8 from the worker thread but that's absolutely forbidden.  V8 is not MT-safe.

**Comment by mbroadst** [comment]
@bnoordhuis I've come to realize that's the case, but I'm still unclear as to the best path forward. Is there a way to do this without having to use uv_async_send?

**Comment by bnoordhuis** [comment]
Rereading your original message, I believe NanAsyncWorker may not be a good fit for your use case.  It's intended for well-defined units of work but I get the impression that the workload is more of an indefinite and long-running nature.  You'd be hogging a thread from the thread pool that way and that's bad because it would affect the throughput of things like crypto, dns, fs, etc.

You should probably look at uv_thread_create() and a uv_async_t coupled with a uv_mutex_t.

**Comment by mbroadst** [comment]
@bnoordhuis fair enough, I imagine in that case I would still have the problem of trying to call into v8. Are there any examples laying around of doing something like this with the bare libuv method you mentioned?

**Comment by bnoordhuis** [comment]
Not any that come to mind but the basic mode of operation is pretty straightforward: you initialize the uv_async_t and uv_mutex_t, create a thread, and whenever the thread completes a unit of work, it grabs the mutex, pushes the work item onto a ready list and calls uv_async_send() to wake up the main thread.  (Don't forget to release the mutex again, of course. :-))

The callback on the main thread grabs the mutex in turn, pops the item from the list and makes the callback.

**Comment by mbroadst** [comment]
@bnoordhuis thanks for the help! sorry I forgot to close this guy.
