### ISSUE TITLE
what does --gc do in tests?

### ISSUE THREAD

**Issue by ralphtheninja** [rvagg/nan#295]
The tests run as `tap --gc test/js/*-test.js`. What does the `--gc` flag do?

**Comment by bnoordhuis** [comment]
You mean `--expose_gc`?  It's a V8 flag that exposes a global `gc()` function that tells V8 to run the garbage collector.

**Comment by ralphtheninja** [comment]
Nope I mean `--gc` :) (Check package.json)

**Comment by mathiask88** [comment]
```--gc``` is a shorthand parameter for ```--expose-gc``` in the tap module so that the ```gc()``` function is present in tests.

**Comment by ralphtheninja** [comment]
Thanks for quick reply guys! Closing.
