### ISSUE TITLE
node -e "require('nan')"' returned exit status 1. while trying to load binding.gyp

### ISSUE THREAD

**Issue by srossross** [rvagg/nan#296]
```
child_process: customFds option is deprecated, use stdio instead.
module.js:338
    throw err;
          ^
Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at [eval]:1:1
    at Object.exports.runInThisContext (vm.js:74:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:460:26)
    at evalScript (node.js:431:25)
    at startup (node.js:90:7)
gyp: Call to 'node -e "require('nan')"' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
```

**Comment by XadillaX** [comment]
it seems you haven't installed nan yet.

**Comment by srossross** [comment]
Sorry, I should hav given more context. This happens when I include nan in my `binding.gyp` file like the example files show.

```js
{
  'targets': [
    {
      'target_name': 'module',
      'sources': [ 'module.cc' ],

      'include_dirs': [
        "<!(node -e \"require('nan')\")"
      ]
    }
  ]
}
```

Is there a way to install nan automatically before running the  `include_dirs` of `node-gyp build`?

**Comment by XadillaX** [comment]
@srossross you should write `nan` down in `package.json`, the `dependencies` section.

**Comment by srossross** [comment]
This is in my package.json as:
```
  "dependencies": {
    "nan": "1.1.0"
  },
```

**Comment by beeven** [comment]
@srossross add ''' "gypfile": true ''' to package.json, then use '''npm install''' to build your package. It'll install nan automatically.

**Comment by srossross** [comment]
Thanks!

**Comment by ispires** [comment]
..issue on Ubuntu Trusty.     You have to set NODE_PATH=..path/to/global/node_modules .....and than it works to find nan after installing it ( npm install -g nan)  - node -e "require('nan')" works after this ..

**Comment by TonyNazzal** [comment]
The problem might be a conflicting package that sets "/usr/sbin/node" to something not nodejs related. This may cause the test to fail.

> node -e "require('nan')"
